#!/bin/bash
#SBATCH --job-name=htseq_count --output=z01.%x
#SBATCH --mail-type=END,FAIL --mail-user=gho7@georgetown.edu
#SBATCH --nodes=1 --ntasks=1 --cpus-per-task=1 --time=72:00:00
#SBATCH --mem=4G


## script uses htseq to count and assign reads to genes

source activate htseq

#-------------------------------------#
# set variables
#-------------------------------------#

# where to find specific algorithm/module (htseq)
htseq=/home/gho7/.conda/envs/htseq/bin/htseq-count

#input BAM file
bam=/home/gho7/samtools/WTA2.srt.bam

#output file
output=/home/gho7/WTA2_htseqCount.txt

# reference GTF file
refGTF=/home/gho7/raw_inputs/GCF_000182965.3_ASM18296v3_genomic.gtf

# run htseq-count
${htseq} -f bam -s no -r pos -i gene_id ${bam} ${refGTF} > ${output}
